// <auto-generated />
using CreditGuard.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CreditGuard.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260401185826_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("CreditGuard.Core.Entities.Credit", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("DailyInstallment")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EndDate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("StartDate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalInterest")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalPrincipal")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Credits");
                });

            modelBuilder.Entity("CreditGuard.Core.Entities.Creditor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Creditors");
                });

            modelBuilder.Entity("CreditGuard.Core.Entities.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Aadhaar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Aadhaar")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CreditGuard.Core.Entities.CustomerGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupLeaderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupPhotoId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupLeaderId");

                    b.ToTable("CustomerGroups");
                });

            modelBuilder.Entity("CreditGuard.Core.Entities.DailyCollection", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountPaid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CollectedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CollectionDate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreditId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdvancePayment")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CollectedBy");

                    b.HasIndex("CreditId");

                    b.ToTable("DailyCollections");
                });

            modelBuilder.Entity("CreditGuard.Core.Entities.GroupMember", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Ratio")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("CreditGuard.Core.Entities.PaymentAllocation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountAllocated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DailyCollectionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DailyCollectionId");

                    b.ToTable("PaymentAllocations");
                });

            modelBuilder.Entity("CreditGuard.Core.Entities.WalletTransaction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreditorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreditorId");

                    b.ToTable("WalletTransactions");
                });

            modelBuilder.Entity("CreditGuard.Core.Entities.Credit", b =>
                {
                    b.HasOne("CreditGuard.Core.Entities.CustomerGroup", "Group")
                        .WithMany("Credits")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("CreditGuard.Core.Entities.CustomerGroup", b =>
                {
                    b.HasOne("CreditGuard.Core.Entities.Customer", "GroupLeader")
                        .WithMany()
                        .HasForeignKey("GroupLeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupLeader");
                });

            modelBuilder.Entity("CreditGuard.Core.Entities.DailyCollection", b =>
                {
                    b.HasOne("CreditGuard.Core.Entities.Creditor", "Creditor")
                        .WithMany()
                        .HasForeignKey("CollectedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CreditGuard.Core.Entities.Credit", "Credit")
                        .WithMany("DailyCollections")
                        .HasForeignKey("CreditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credit");

                    b.Navigation("Creditor");
                });

            modelBuilder.Entity("CreditGuard.Core.Entities.GroupMember", b =>
                {
                    b.HasOne("CreditGuard.Core.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CreditGuard.Core.Entities.CustomerGroup", "Group")
                        .WithMany("GroupMembers")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("CreditGuard.Core.Entities.PaymentAllocation", b =>
                {
                    b.HasOne("CreditGuard.Core.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CreditGuard.Core.Entities.DailyCollection", "DailyCollection")
                        .WithMany("PaymentAllocations")
                        .HasForeignKey("DailyCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("DailyCollection");
                });

            modelBuilder.Entity("CreditGuard.Core.Entities.WalletTransaction", b =>
                {
                    b.HasOne("CreditGuard.Core.Entities.Creditor", "Creditor")
                        .WithMany("WalletTransactions")
                        .HasForeignKey("CreditorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creditor");
                });

            modelBuilder.Entity("CreditGuard.Core.Entities.Credit", b =>
                {
                    b.Navigation("DailyCollections");
                });

            modelBuilder.Entity("CreditGuard.Core.Entities.Creditor", b =>
                {
                    b.Navigation("WalletTransactions");
                });

            modelBuilder.Entity("CreditGuard.Core.Entities.CustomerGroup", b =>
                {
                    b.Navigation("Credits");

                    b.Navigation("GroupMembers");
                });

            modelBuilder.Entity("CreditGuard.Core.Entities.DailyCollection", b =>
                {
                    b.Navigation("PaymentAllocations");
                });
#pragma warning restore 612, 618
        }
    }
}
